### ISSUE TITLE
My prompt does not look like yours.

### ISSUE THREAD

**Issue by ziimoo** [sindresorhus/hyperterm-snazzy#1]
When I added this plugin my prompt does not look like this. See below image for what i see.

![screen shot 2016-07-25 at 1 14 28 am](https://cloud.githubusercontent.com/assets/246315/17091105/2969e296-5205-11e6-8751-a8b4714e4a49.png)

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/hyperterm-snazzy/commit/c17418282c3e1f2d714e179d139c368fe9ca027d
