### ISSUE TITLE
Question: Blocks of colors for screenshot?

### ISSUE THREAD

**Issue by BenDiuguid** [sindresorhus/hyperterm-snazzy#4]
Hey @sindresorhus,

Awesome work!

I was just curious how you got the different blocks of colors for the screenshot that you took?

Thanks!

**Comment by sindresorhus** [comment]
http://askubuntu.com/questions/27314/script-to-display-all-terminal-colors/279014#279014

And just scroll to the bottom part.

**Comment by BenDiuguid** [comment]
Thanks so much!
